/** @category Contracts / Client */
export class ExpiredStateError extends Error {}
/** @category Contracts / Client */
export class RestoreFailureError extends Error {}
/** @category Contracts / Client */
export class NeedsMoreSignaturesError extends Error {}
/** @category Contracts / Client */
export class NoSignatureNeededError extends Error {}
/** @category Contracts / Client */
export class NoUnsignedNonInvokerAuthEntriesError extends Error {}
/** @category Contracts / Client */
export class NoSignerError extends Error {}
/** @category Contracts / Client */
export class NotYetSimulatedError extends Error {}
/** @category Contracts / Client */
export class FakeAccountError extends Error {}
/** @category Contracts / Client */
export class SimulationFailedError extends Error {}
/** @category Contracts / Client */
export class InternalWalletError extends Error {}
/** @category Contracts / Client */
export class ExternalServiceError extends Error {}
/** @category Contracts / Client */
export class InvalidClientRequestError extends Error {}
/** @category Contracts / Client */
export class UserRejectedError extends Error {}
