/**
 * Generates public/.htaccess from config/site.ts. The file enables two
 * agent-friendly response behaviors on Apache:
 *
 *   1. Link response headers (RFC 8288) advertising the LLMs bundles.
 *   2. Markdown content negotiation: when the client sends
 *      `Accept: text/markdown` and a sibling .md file exists for the
 *      requested page, serve that instead of the HTML.
 *
 * Apache-only. The generated file is inert on hosts that don't honor
 * .htaccess (GitHub Pages, Cloudflare Pages, Netlify, S3). For those
 * hosts the same behaviors must be implemented in the host's native
 * format (e.g. _headers for CF/Netlify, edge functions for GH Pages).
 *
 * Sibling to scripts/build-robots.ts; both write into the gitignored
 * public/ tree so Astro picks them up at site-root paths.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { BASE_PATH } from "../config/site.js";

const REPO_ROOT = process.cwd();
const PUBLIC_DIR = join(REPO_ROOT, "public");
const HTACCESS_OUT = join(PUBLIC_DIR, ".htaccess");

function renderLinkHeader(): string {
  // RFC 8288: comma-separated list of links, each `<URI>; rel="..."; type="..."`.
  // Inside Apache's quoted Header directive, double quotes must be backslash-escaped.
  const llms = `<${BASE_PATH}/llms.txt>; rel=\\"alternate\\"; type=\\"text/plain\\"`;
  const llmsFull = `<${BASE_PATH}/llms-full.txt>; rel=\\"alternate\\"; type=\\"text/plain\\"`;
  return `${llms}, ${llmsFull}`;
}

function renderHtaccess(): string {
  return `# Generated by scripts/build-htaccess.ts from config/site.ts.
# Edit that file (or this script) and rebuild via \`pnpm docs:htaccess\`.
#
# Apache-only directives. This file is inert on static hosts that don't
# read .htaccess (GitHub Pages, Cloudflare Pages, Netlify, S3). For those
# hosts the same behaviors must be expressed in their native formats.
#
# DOCUMENT_ROOT caveat: the markdown-negotiation file checks below assume
# the site is deployed at the apex of an Apache vhost (current setup on
# stellar-sdk.quietbits.com). If you ever upload dist/site/ into a non-
# root subdirectory of an Apache host, %{DOCUMENT_ROOT}/1.md will look
# in the wrong place and the rewrite will silently no-op (Apache will
# serve the original HTML). Adjust by prepending the subdirectory or
# switching to %{REQUEST_FILENAME}-based checks.

<IfModule mod_headers.c>
  # Apache: Link response header for agent discovery (RFC 8288).
  # Advertises both LLMs bundles on every response.
  Header set Link "${renderLinkHeader()}"

  # Apache: tell caches/CDNs that responses vary by Accept header so
  # markdown and HTML variants of the same URL don't cross-pollute caches.
  Header append Vary Accept
</IfModule>

<IfModule mod_rewrite.c>
  RewriteEngine On

  # Apache: markdown content negotiation. When the client prefers
  # text/markdown and a sibling .md file exists at the requested path,
  # serve that instead of the HTML render.

  # Homepage special case: GET / + Accept: text/markdown  →  /index.md
  RewriteCond %{HTTP_ACCEPT} text/markdown
  RewriteCond %{DOCUMENT_ROOT}/index.md -f
  RewriteRule ^/?$ /index.md [L]

  # All other pages with trailing slash: /foo/bar/  →  /foo/bar.md
  RewriteCond %{HTTP_ACCEPT} text/markdown
  RewriteCond %{DOCUMENT_ROOT}/$1.md -f
  RewriteRule ^/?(.+?)/?$ /$1.md [L]
</IfModule>
`;
}

function main(): void {
  const content = renderHtaccess();
  mkdirSync(PUBLIC_DIR, { recursive: true });
  writeFileSync(HTACCESS_OUT, content, "utf8");
  console.log(`Wrote ${HTACCESS_OUT} (${content.length}B).`);
}

main();
