#!/usr/bin/env bash

set -euo pipefail

# Get script directory and repo root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Download the Stellar Asset Contract spec XDR
REPO_URL="https://raw.githubusercontent.com/stellar/stellar-asset-contract-spec/main/stellar-asset-spec.xdr"
OUTPUT_FILE="$REPO_ROOT/stellar-asset-spec.xdr"
TS_FILE="$REPO_ROOT/src/bindings/sac-spec.ts"

echo "Downloading Stellar Asset Contract spec from GitHub..."

# Download with error handling
if ! curl -fsSL "$REPO_URL" -o "$OUTPUT_FILE"; then
  echo "✗ Failed to download from $REPO_URL"
  exit 1
fi

# Verify file was downloaded and has content
if [ ! -s "$OUTPUT_FILE" ]; then
  echo "✗ Downloaded file is empty or doesn't exist"
  rm -f "$OUTPUT_FILE"
  exit 1
fi

echo "✓ Successfully downloaded $OUTPUT_FILE"
echo "  Size: $(wc -c < "$OUTPUT_FILE") bytes"

# Convert to base64 (portable for both macOS and Linux)
echo "Converting to base64..."
if command -v base64 >/dev/null 2>&1; then
  # Try macOS syntax first, fall back to Linux
  BASE64_CONTENT=$(base64 -i "$OUTPUT_FILE" 2>/dev/null || base64 -w 0 "$OUTPUT_FILE" 2>/dev/null || base64 "$OUTPUT_FILE" | tr -d '\n')
else
  echo "✗ base64 command not found"
  rm -f "$OUTPUT_FILE"
  exit 1
fi

# Validate base64 content
if [ -z "$BASE64_CONTENT" ]; then
  echo "✗ Base64 conversion failed"
  rm -f "$OUTPUT_FILE"
  exit 1
fi

# Update TypeScript file using printf to avoid shell interpretation
echo "Updating $TS_FILE..."
{
  echo "// Auto-generated by scripts/download-sac-spec.sh"
  echo "// Do not edit manually - run the script to update"
  printf 'export const SAC_SPEC = "%s";\n' "$BASE64_CONTENT"
} > "$TS_FILE"

echo "✓ Successfully updated $TS_FILE"

# Cleanup downloaded file
rm -f "$OUTPUT_FILE"
echo "✓ Cleaned up temporary file" d
