name: npm publish
on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Upgrade npm for OIDC trusted publishing
        run: npm install -g npm@^11.5.1

      - name: Enable Corepack
        run: corepack enable

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --network-concurrency 1

      - name: Install Playwright
        run: pnpm exec playwright install --with-deps chromium firefox

      - name: Build, Test, and Package
        run: pnpm run preversion

      - name: Publish npm package
        run: npm publish --access public --provenance
