name: npm publish
on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Upgrade npm for OIDC trusted publishing
        run: npm install -g npm@^11.5.1

      - name: Install Dependencies
        run: yarn install

      - name: Install Playwright
        run: yarn playwright install --with-deps chromium firefox

      - name: Build, Test, and Package
        run: yarn preversion

      - name: Publish npm package to both places
        run: npm publish --access public --provenance
